[project]
name = "pyduktape3"
version = "0.1.2"
description = "Yet another pyduktape fork written in Cython wrapped around duktape 3.0"
readme = "README.md"
authors = [
    { name = "Vizonex", email = "VizonexBusiness@gmail.com" }
]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "cython", "wheel"]

[tool.setuptools]
# Things I learned from cyares were brought over here...
zip-safe = false
# Important tip: use packages arguments they help with not needing a src directory...
packages = ['pyduktape3']

ext-modules = [
{name = "pyduktape3._pyduktape3", sources = ["pyduktape3/_pyduktape3.pyx", "vendor/duktape.c", "vendor/duk_module_duktape.c"], include-dirs=['vendor', 'pyduktape3']}
]

[project.urls]
    repository = "https://github.com/Vizonex/pyduktape3.git"
